name: omniQTL
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12.12
  - setuptools=80.9.0
  - numpy=2.4.1
  - pandas=3.0.0
  - pip
  - pip:
      - -r requirements.txt
      - -e .
