"""Genotyping-array QC and imputation pipeline utilities.

This module handles genotyping-array QC, pre-imputation checks, submission of
prepared VCFs to the TOPMed and Michigan imputation servers, retrieval and
post-processing of imputation results, and general VCF manipulation (merging,
sample subsetting/renaming, dbSNP rsID annotation, and MAF/MAC/imputation-R2
filtering).
"""
from typing import Any

from .utils import *
from .qc import ArrayQC


class Genotyping(ArrayQC):
    """Genotyping-array QC and imputation pipeline for a PLINK bfile set.

    Inherits the PLINK-based genotyping-array QC steps from
    :class:`~omniQTL.qc.ArrayQC` and adds the pre-imputation checks,
    TOPMed/Michigan imputation-server submission and result retrieval, and
    downstream VCF manipulation steps (merge, subset, rename, annotate,
    filter) needed to produce analysis-ready imputed genotypes.

    Attributes:
        bfile: Prefix (without extension) of the PLINK binary fileset being
            processed.
        output_prefix: Prefix used for QC'd output files, derived from
            `bfile`.
        chroms: List of autosomal chromosome labels (`'chr1'`..`'chr22'`)
            used when iterating over per-chromosome imputation output.
    """

    def __init__(self, bfile: str = 'TIGER') -> None:
        """Initialize the Genotyping pipeline.

        Args:
            bfile: Prefix (without extension) of the PLINK binary fileset
                (.bed/.bim/.fam) to process.
        """
        super().__init__()
        self.bfile = bfile
        self.output_prefix = f'{self.bfile}_QCed'
        self.chroms = [f'chr{n}' for n in range(1, 23)]

    def pre_imputation_check(
        self,
        pre_imputation_check_script: str | None = None,
        ref_file: str | None = None,
        ref_name: str = '1000g',
        pop: str = 'ALL',
        update_script: str = 'Run-plink.sh',
    ) -> None:
        """Run Will Rayner's HRC-1000G-check-bim.pl tool on the QC'd bfile.

        Computes allele frequencies for `self.output_prefix` with PLINK,
        runs the HRC-1000G-check-bim.pl pre-imputation check script against
        the reference legend file, executes the resulting PLINK update
        script to produce per-chromosome VCFs, and then bgzips/tabix-indexes
        each output VCF.

        Args:
            pre_imputation_check_script: Path to HRC-1000G-check-bim.pl. If
                None, defaults to the bundled vendor copy under
                `vendor/pre_imputation_check/`.
            ref_file: Path to the reference legend file (e.g. the 1000G
                Phase 3 combined legend). If None, defaults to the bundled
                vendor copy under `vendor/pre_imputation_check/`.
            ref_name: Reference panel flag passed to the check script (e.g.
                `'1000g'` or `'hrc'`).
            pop: Population code passed to the check script (e.g. `'ALL'`).
            update_script: Filename of the PLINK update script generated by
                the check script, expected inside the check-script output
                directory.

        Raises:
            FileNotFoundError: If `pre_imputation_check_script` or
                `ref_file` does not exist, if the generated `update_script`
                is not found in the check-script output directory, or if the
                check-script output directory does not exist afterward.
        """
        if pre_imputation_check_script is None:
            pre_imputation_check_script = str(
                BASE.parent.parent / 'vendor/pre_imputation_check/HRC-1000G-check-bim.pl'
            )
        if ref_file is None:
            ref_file = str(
                BASE.parent.parent / 'vendor/pre_imputation_check/1000GP_Phase3_combined.legend'
            )

        out_dir = f'{self.output_prefix}_checked'
        if os.path.exists(pre_imputation_check_script) and os.path.exists(ref_file):
            cmd = f'plink --bfile {self.output_prefix} --freq --out {self.output_prefix}'
            subprocess.run(cmd, shell=True)
            cmd = (
                f'perl {pre_imputation_check_script} --bim {self.output_prefix}.bim '
                f'--frequency {self.output_prefix}.frq -r {ref_file} --{ref_name} --pop {pop} --out {out_dir}'
            )
            subprocess.run(cmd, shell=True)
            run_script_path = f'{out_dir}/{update_script}'
            if os.path.exists(run_script_path):
                cmd = f'bash {run_script_path}'
                subprocess.run(cmd, shell=True)
            else:
                raise FileNotFoundError(
                    f"Run script generated by pre-imputation check not found at {run_script_path}"
                )
        else:
            raise FileNotFoundError(f"Pre-imputation check script or reference file not found")

        if not os.path.exists(out_dir):
            raise FileNotFoundError(f"Output directory {out_dir} not found after pre-imputation check")

        vcfs = sorted([f'{out_dir}/{f}' for f in os.listdir(out_dir) if f.endswith('.vcf')])
        for vcf in vcfs:
            cmd = f'bgzip -f {vcf}; tabix -p vcf {vcf}.gz'
            print(cmd)
            subprocess.run(cmd, shell=True)

    def submit_to_topmed(self, config_file: str = 'config.yaml', job_name: str | None = None) -> None:
        """Submit the pre-imputation-checked, per-chromosome VCFs to TOPMed.

        Loads TOPMed API settings (url, version, token, refpanel,
        population, phasing) from `config_file` and POSTs the checked VCFs
        (restricted to `self.chroms`) to the TOPMed imputation server API
        via curl.

        Args:
            config_file: Path to a YAML config file. If it does not exist
                as given, it is looked up under the package `config`
                directory instead.
            job_name: Name to assign to the imputation job. Defaults to
                `self.bfile` if None.

        Raises:
            FileNotFoundError: If neither the given `config_file` path nor
                the package-relative fallback path exists.
            KeyError: If required TOPMed configuration keys
                (`TOPMed.url`, `TOPMed.version`, `TOPMed.token`,
                `TOPMed.refpanel`, `TOPMed.population`, `TOPMed.phasing`)
                are missing from the loaded config.
        """
        if job_name is None:
            job_name = f'{self.bfile}'
        in_dir = f'{self.output_prefix}_checked'
        if not os.path.exists(in_dir):
            raise FileNotFoundError(f"Input directory {in_dir} not found")
        cwd = os.getcwd()
        os.chdir(in_dir)
        vcfs = sorted([
            f for f in os.listdir('.')
            if f.endswith('.vcf.gz') and f.split('.vcf.gz')[0].split('-')[-1] in self.chroms
        ])

        if os.path.exists(config_file):
            with open(config_file, 'r') as f:
                config = yaml.safe_load(f)
        else:
            config_file = str(BASE / 'config' / config_file)
            config_template = str(BASE / 'config/config_template.yaml')
            if os.path.exists(config_file):
                with open(config_file, 'r') as f:
                    config = yaml.safe_load(f)
            else:
                raise FileNotFoundError(
                    f"Config file not found. Please provide one with reference to the template: "
                    f"{config_template}"
                )

        try:
            url = config['TOPMed']['url']
            version = config['TOPMed']['version']
            token = config['TOPMed']['token']
            refpanel = config['TOPMed']['refpanel']
            population = config['TOPMed']['population']
            phasing = config['TOPMed']['phasing']
            cmd = (
                f'curl {url}@{version} -H "X-Auth-Token: {token}" -F "refpanel={refpanel}" '
                f'-F "job-name={job_name}" -F "population={population}" -F "input-phasing={phasing}" '
            )
            for vcf in vcfs:
                cmd += f'-F "files=@{vcf}" '
            print(cmd)
            subprocess.run(cmd, shell=True)

        except Exception as e:
            raise KeyError(f"Missing required TOPMed configuration parameters: {e}")
        os.chdir(cwd)

    def submit_to_michigan_for_hla_imputation(
        self,
        vcf_file: str,
        config_file: str = 'config.yaml',
        job_name: str | None = None,
        refpanel: str | None = None,
    ) -> None:
        """Submit a single VCF to the Michigan Imputation Server for HLA imputation.

        Loads Michigan API settings (url, token, refpanel, phasing) from
        `config_file` and POSTs `vcf_file` to the Michigan imputation server
        API via curl.

        Args:
            vcf_file: Path to the VCF file to submit for HLA imputation.
            config_file: Path to a YAML config file. If it does not exist
                as given, it is looked up under the package `config`
                directory instead.
            job_name: Name to assign to the imputation job. Defaults to
                `self.bfile` if None.
            refpanel: Reference panel to use. If None, falls back to
                `Michigan.refpanel` from the loaded config.

        Raises:
            FileNotFoundError: If neither the given `config_file` path nor
                the package-relative fallback path exists.
            KeyError: If required Michigan configuration keys
                (`Michigan.url`, `Michigan.token`, `Michigan.refpanel`,
                `Michigan.phasing`) are missing from the loaded config.
        """
        if job_name is None:
            job_name = f'{self.bfile}'
        in_dir = f'{self.output_prefix}_checked'
        if not os.path.exists(in_dir):
            raise FileNotFoundError(f"Input directory {in_dir} not found")
        cwd = os.getcwd()
        os.chdir(in_dir)

        if os.path.exists(config_file):
            with open(config_file, 'r') as f:
                config = yaml.safe_load(f)
        else:
            config_file = str(BASE / 'config' / config_file)
            config_template = str(BASE / 'config/config_template.yaml')
            if os.path.exists(config_file):
                with open(config_file, 'r') as f:
                    config = yaml.safe_load(f)
            else:
                raise FileNotFoundError(
                    f"Config file not found. Please provide one with reference to the template: "
                    f"{config_template}"
                )

        try:
            url = config['Michigan']['url']
            token = config['Michigan']['token']
            if refpanel is None:
                refpanel = config['Michigan']['refpanel']
            phasing = config['Michigan']['phasing']
            cmd = (
                f'curl {url} -H "X-Auth-Token: {token}" -F "refpanel={refpanel}" '
                f'-F "job-name={job_name}" -F "input-phasing={phasing}" '
            )
            for vcf in [vcf_file]:
                cmd += f'-F "files=@{vcf}" '
            print(cmd)
            subprocess.run(cmd, shell=True)

        except Exception as e:
            raise KeyError(f"Missing required Michigan configuration parameters: {e}")
        os.chdir(cwd)

    def get_topmed_results(
        self,
        cmd: str,
        password: str,
        out_dir: str | None = None,
        exclude_typed_only_variants: bool = True,
        n_threads: int = 4,
    ) -> None:
        """Download, decrypt, and post-process TOPMed imputation results.

        Runs `cmd` (typically a set of wget/curl download commands provided
        by the TOPMed job results page) inside `out_dir`, unzips the
        password-protected per-chromosome result archives, concatenates the
        per-chromosome dosage VCFs (restricted to `self.chroms`) with
        bcftools, optionally filters out typed-only (non-imputed) variants,
        and converts the final VCF to a PLINK bfile.

        Args:
            cmd: Shell command used to download the TOPMed result archives
                into `out_dir`.
            password: Password used to decrypt the downloaded zip archives.
            out_dir: Directory to download and process results in. Defaults
                to `f'{self.bfile}_TOPMed'` if None; created if missing.
            exclude_typed_only_variants: If True, keep only variants with
                `INFO/IMPUTED=1`; otherwise keep all concatenated variants.
            n_threads: Number of threads passed to bcftools operations.
        """
        if out_dir is None:
            out_dir = f'{self.bfile}_TOPMed'
        if not os.path.exists(out_dir):
            os.makedirs(out_dir)
        cwd = os.getcwd()
        os.chdir(out_dir)
        subprocess.run(cmd, shell=True)

        fs = [f for f in os.listdir('.') if f.find('chr') == 0 and f.endswith('.zip')]
        for f in fs:
            cmd = f'unzip -P"{password}" {f}'
            subprocess.run(cmd, shell=True)

        vcfs = []
        for ch in self.chroms:
            f = f'{ch}.dose.vcf.gz'
            cmd = f'tabix -p vcf {f}'
            if os.path.exists(f):
                subprocess.run(cmd, shell=True)
                vcfs.append(f)
            else:
                print(f"Warning: Expected VCF file {f} not found in TOPMed results")

        in_file = f'{self.bfile}_concated.vcf.gz'
        out_file = f'{self.bfile}_imputed.vcf.gz'
        cmd = f'bcftools concat --threads {n_threads} {" ".join(vcfs)} -Oz -o {in_file}; tabix -p vcf {in_file}'
        subprocess.run(cmd, shell=True)
        if exclude_typed_only_variants:
            cmd = f'''bcftools view -i 'INFO/IMPUTED=1' --threads {n_threads} {in_file} -Oz -o {out_file}; tabix -p vcf {out_file}'''
            subprocess.run(cmd, shell=True)
        else:
            os.rename(in_file, out_file)
            os.rename(in_file + '.tbi', out_file + '.tbi')

        cmd = f'plink2 --vcf {out_file} --make-bed --out {out_file.split(".vcf")[0]}'
        subprocess.run(cmd, shell=True)
        os.chdir(cwd)

    def get_michigan_hla_results(
        self,
        cmd: str,
        password: str,
        out_dir: str | None = None,
        n_threads: int = 4,
    ) -> None:
        """Download, decrypt, and post-process Michigan HLA imputation results.

        Runs `cmd` (typically a set of wget/curl download commands provided
        by the Michigan Imputation Server job results page) inside
        `out_dir`, unzips the password-protected result archives, links the
        chr6 dosage VCF to a named output file, indexes it with bcftools,
        and converts it to a PLINK bfile.

        Args:
            cmd: Shell command used to download the Michigan result
                archives into `out_dir`.
            password: Password used to decrypt the downloaded zip archives.
            out_dir: Directory to download and process results in. Defaults
                to `f'{self.bfile}_MichiganHLA'` if None; created if
                missing.
            n_threads: Unused by this method's own commands; retained for
                interface symmetry with related methods.
        """
        if out_dir is None:
            out_dir = f'{self.bfile}_MichiganHLA'
        if not os.path.exists(out_dir):
            os.makedirs(out_dir)
        cwd = os.getcwd()
        os.chdir(out_dir)
        subprocess.run(cmd, shell=True)

        fs = [f for f in os.listdir('.') if f.find('chr') == 0 and f.endswith('.zip')]
        for f in fs:
            cmd = f'unzip -P "{password}" {f}'
            subprocess.run(cmd, shell=True)

        in_file = f'chr6.dose.vcf.gz'
        out_file = f'{self.bfile}_imputedHLA.vcf.gz'
        cmd = (
            f'ln {in_file} {out_file}; bcftools index {out_file}; '
            f'plink2 --vcf {out_file} --make-bed --out {out_file.split(".vcf")[0]}'
        )
        subprocess.run(cmd, shell=True)
        os.chdir(cwd)

    def merge_vcfs(
        self,
        vcf_files: list[str],
        output_vcf: str,
        n_threads: int = 4,
        params: dict[str, Any] = {'R2': 'avg'},
        force_samples: bool = False,
    ) -> None:
        """Merge multiple VCFs into a single output VCF with bcftools.

        Builds a `-i` include-tag-combining-rule string from `params` (e.g.
        `{'R2': 'avg'}` averages the R2 INFO field across merged records)
        and runs `bcftools merge`, then tabix-indexes the result.

        Args:
            vcf_files: Paths of the VCF files to merge.
            output_vcf: Path of the merged output VCF (bgzipped).
            n_threads: Number of threads passed to `bcftools merge`.
            params: Mapping of INFO field name to combining rule, joined
                into bcftools' `-i key:value,...` merge-info-rule syntax.
            force_samples: If True, pass `--force-samples` to `bcftools
                merge` to resolve duplicate sample names across inputs.
        """
        params_str = ','.join([f'{key}:{value}' for key, value in params.items()])
        if params_str:
            params_str = f'-i {params_str}'
        if force_samples:
            cmd = (
                f'bcftools merge -Oz -o {output_vcf} --force-samples --threads {n_threads} '
                f'{params_str} {" ".join(vcf_files)}; tabix -p vcf {output_vcf}'
            )
        else:
            cmd = (
                f'bcftools merge -Oz -o {output_vcf} --threads {n_threads} '
                f'{params_str} {" ".join(vcf_files)}; tabix -p vcf {output_vcf}'
            )
        print(cmd)
        subprocess.run(cmd, shell=True)

    def subset_samples_vcf(
        self,
        vcf_file: str,
        sample_list: str,
        output_vcf: str,
        n_threads: int = 4,
    ) -> None:
        """Subset a VCF down to a given list of samples with bcftools.

        Args:
            vcf_file: Path of the input VCF file.
            sample_list: Path to a file listing the sample IDs to keep
                (passed to `bcftools view -S`).
            output_vcf: Path of the subsetted output VCF (bgzipped).
            n_threads: Number of threads passed to `bcftools view`.
        """
        cmd = f'bcftools view --threads {n_threads} -S {sample_list} {vcf_file} -Oz -o {output_vcf}; tabix -p vcf {output_vcf}'
        print(cmd)
        subprocess.run(cmd, shell=True)

    def rename_samples_vcf(
        self,
        vcf_file: str,
        sample_mapping_file: str,
        sort_samples: bool = True,
        n_thresholds: int = 4,
    ) -> None:
        """Rename VCF sample IDs and optionally sort samples.

        Runs `bcftools reheader` with `sample_mapping_file` to rename
        samples, writing to a new `_sampleRenamed.vcf.gz` file. If
        `sort_samples` is True, the renamed samples are additionally sorted
        alphabetically and the VCF is rewritten in that sample order,
        replacing the renamed output in place.

        Args:
            vcf_file: Path of the input VCF file.
            sample_mapping_file: Path to the old-to-new sample name mapping
                file passed to `bcftools reheader -s`.
            sort_samples: If True, sort samples alphabetically after
                renaming.
            n_thresholds: Number of threads passed to the sample-sorting
                `bcftools view` step (note: unused by the initial
                `bcftools reheader` step).
        """
        out_file = vcf_file.replace('.vcf.gz', '_sampleRenamed.vcf.gz')
        cmd = f'bcftools reheader -s {sample_mapping_file} {vcf_file} -o {out_file}; tabix -p vcf {out_file}'
        subprocess.run(cmd, shell=True)
        if sort_samples:
            out_file_tmp = out_file.replace('.vcf.gz', '_tmp.vcf.gz')
            samples_sorted = out_file.replace('.vcf.gz', '_samples_sorted.txt')
            cmd = f'bcftools query -l {out_file}| sort > {samples_sorted}'
            subprocess.run(cmd, shell=True)
            cmd = (
                f'bcftools view --threads {n_thresholds} -S {samples_sorted} {out_file} -Oz -o {out_file_tmp}; '
                f'tabix -p vcf {out_file_tmp}'
            )
            subprocess.run(cmd, shell=True)
            os.rename(out_file_tmp, out_file)
            os.rename(f'{out_file_tmp}.tbi', f'{out_file}.tbi')

    def annotate_variants_vcf(
        self,
        vcf_file: str,
        dbsnp_vcf: str = 'dbSNP_hg38.gz',
        ref_fa: str = 'hg38.fa',
        norm_variants: bool = True,
        dbsnp_url: str = 'https://ftp.ncbi.nih.gov/snp/latest_release/VCF/',
        id_col: str = 'ID',
        id_name: str = r'%CHROM\_%POS\_%REF\_%FIRST_ALT',
        n_threads: int = 4,
    ) -> None:
        """Normalize and annotate VCF variant IDs with dbSNP rsIDs.

        Optionally left-normalizes and splits multiallelic sites with
        `bcftools norm`, annotates the `ID` column from `dbsnp_vcf` with
        `bcftools annotate -c`, then rewrites any still-unannotated IDs
        using the `id_name` template with `bcftools annotate --set-id`.

        Args:
            vcf_file: Path of the input VCF file to annotate.
            dbsnp_vcf: Path to a tabix-indexed dbSNP VCF used as the
                annotation source.
            ref_fa: Path to the reference FASTA used for normalization.
            norm_variants: If True, run `bcftools norm` before annotation.
            dbsnp_url: URL documenting where `dbsnp_vcf` can be downloaded
                from; not used to fetch anything within this method.
            id_col: Column to import from `dbsnp_vcf` via `bcftools
                annotate -c` (typically `'ID'`).
            id_name: `bcftools annotate --set-id` template used to fill in
                IDs for variants not annotated from dbSNP.
            n_threads: Number of threads passed to bcftools operations.

        Raises:
            FileNotFoundError: If `dbsnp_vcf` does not exist (raised twice
                in this method: once checking `dbsnp_vcf` itself, and again
                — despite the error message referring to the reference
                FASTA — checking `dbsnp_vcf` a second time rather than
                `ref_fa`).
        """
        if not os.path.exists(dbsnp_vcf):
            raise FileNotFoundError(f"dbSNP VCF file not found at {dbsnp_vcf}")

        if not os.path.exists(dbsnp_vcf):
            raise FileNotFoundError(f"Reference FASTA file not found at {ref_fa}")

        out_file_norm = vcf_file.split('.vcf')[0] + '_norm.vcf.gz'
        out_file_rs = vcf_file.split('.vcf')[0] + '_rs.vcf.gz'
        out_file_rsID = vcf_file.split('.vcf')[0] + '_rsID.vcf.gz'

        if norm_variants:
            cmd = f'bcftools norm --threads {n_threads} -f {ref_fa} -m -any {vcf_file} -Oz -o {out_file_norm}; tabix -p vcf {out_file_norm}'
            subprocess.run(cmd, shell=True)
            vcf_file = out_file_norm

        cmd = f'bcftools annotate --threads {n_threads} -a {dbsnp_vcf} -c {id_col} -Oz -o {out_file_rs} {vcf_file}'
        subprocess.run(cmd, shell=True)

        cmd = f"bcftools annotate --threads {n_threads} --set-id +'{id_name}' {out_file_rs} -Oz -o {out_file_rsID}; tabix -p vcf {out_file_rsID}"
        subprocess.run(cmd, shell=True)
        os.remove(out_file_rs)

    def filter_variants_vcf(
        self,
        vcf_file: str,
        output_vcf: str | None = None,
        params: dict[str, Any] = {'update_flags': ['AC', 'AN', 'AF', 'MAF'], 'MAF': 0.05, 'R2': 0.8},
        n_threads: int = 4,
    ) -> None:
        """Filter a VCF by MAF/MAC and imputation R2 using bcftools.

        Builds a `bcftools filter` include expression from whichever of the
        `MAF`, `MAC`, and `R2` keys are present in `params` (checked in the
        order: MAF+R2, MAC+R2, MAF only, R2 only), optionally piping the
        input through `bcftools +fill-tags` first (when `params` contains
        `update_flags`) to recompute INFO tags such as AC/AN/AF/MAF before
        filtering.

        Args:
            vcf_file: Path of the input VCF file.
            output_vcf: Path of the filtered output VCF. Defaults to
                `vcf_file` with `.vcf.gz` replaced by
                `_variantFiltered.vcf.gz` if None.
            params: Filtering configuration. Recognized keys are `'MAF'`,
                `'MAC'`, `'R2'` (thresholds used to build the filter
                expression) and `'update_flags'` (list of INFO tags to
                recompute via `bcftools +fill-tags` before filtering).
            n_threads: Number of threads passed to bcftools operations.
        """
        if output_vcf is None:
            output_vcf = vcf_file.replace('.vcf.gz', '_variantFiltered.vcf.gz')

        vcf_file_tmp = vcf_file
        cmd = ''
        expr = ''
        if 'MAF' in params and 'R2' in params:
            expr = f"MAF>{params['MAF']} && R2>{params['R2']}"
        elif 'MAC' in params and 'R2' in params:
            # to be consistent with the GWAS analysis
            expr = f"MAC>={params['MAC']} && R2>{params['R2']}"
        elif 'MAF' in params:
            expr = f"MAF>{params['MAF']}"
        elif 'R2' in params:
            expr = f"R2>{params['R2']}"

        if 'update_flags' in params:
            flags = ','.join([f'{flag}' for flag in params['update_flags']])
            cmd = f'''bcftools +fill-tags --threads {n_threads} {vcf_file} -Ou -- -t {flags} | '''
            vcf_file_tmp = ''
        cmd += f'''bcftools filter --threads {n_threads} -i "{expr}" {vcf_file_tmp} -Oz -o {output_vcf}'''
        print(cmd)
        subprocess.run(cmd, shell=True)
        cmd = f'tabix -p vcf {output_vcf}'
        subprocess.run(cmd, shell=True)

    def vcf_filter_typed_only_variants(
        self,
        vcf_file: str,
        output_vcf: str | None = None,
        n_threads: int = 4,
    ) -> None:
        """Keep only imputed (non-typed-only) variants from a VCF.

        Filters `vcf_file` down to records with `INFO/IMPUTED=1` using
        `bcftools view`, then tabix-indexes the result.

        Args:
            vcf_file: Path of the input VCF file.
            output_vcf: Path of the filtered output VCF. Defaults to
                `vcf_file` with `.vcf.gz` replaced by `_filtered.vcf.gz` if
                None.
            n_threads: Number of threads passed to `bcftools view`.
        """
        if output_vcf is None:
            output_vcf = vcf_file.replace('.vcf.gz', '_filtered.vcf.gz')
        cmd = f'''bcftools view -i 'INFO/IMPUTED=1' --threads {n_threads} {vcf_file} -Oz -o {output_vcf}; tabix -p vcf {output_vcf}'''
        print(cmd)
        subprocess.run(cmd, shell=True)

    def vcf_to_bfile(self, vcf_file: str) -> None:
        """Convert a VCF to a PLINK binary fileset with plink2.

        Args:
            vcf_file: Path of the input VCF file to convert. The output
                bfile prefix is derived by stripping the `.vcf` suffix
                (and anything after it) from `vcf_file`.
        """
        bfile = vcf_file.split('.vcf')[0]
        cmd = f'plink2 --vcf {vcf_file} --make-bed --out {bfile}'
        subprocess.run(cmd, shell=True)
